"service_identity" error when launch Deluge-server <body> I installed Deluge-Server with Macports. When I the install was done I tried to start the service with codedeluged/code when I write this command I get this weird(for me) code"UserWarning"/code. What does it mean I dont have a working  code"service_identity"/code module. I tried to go to https://pypi.python.org/pypi/service_identity . When I go to this page I get a weird "--.whl" file. How do I install this?     DIMIBook:~ cbayrak$ :0: UserWarning: You do not have a working   installation of the service_identity module: 'No module named   service_identity'.   Please install it from https://pypi.python.org/pypi/service_identity and    make sure all of its   dependencies are satisfied. Without the service_identity module and a   recent enough pyOpenSSL to support it, Twisted can perform only   rudimentary TLS client hostname verification. Many valid   certificate/hostname mappings may be rejected.   My questions are;  ol liWhat is a "service_identity" module?     I tried to install it with codepip install service_identity/code    But I get   the same error as the question below. /li liHow do I install a "--.whl" file? I found how to install this extension but when I install "service_identity-16.0.0-py2.py3-none-any.whl" from "https ://pypi.python. org/pypi/service_identity#downloads" I get an error:/li /ol     DIMIBook:~ cbayrak$ pip install   /Users/cbayrak/Downloads/service_identity-16.0.0-py2.py3-none-any.whl    Processing ./Downloads/service_identity-16.0.0-py2.py3-none-any.whl   Collecting pyasn1 (from service-identity==16.0.0)   Using cached   pyasn1-0.1.9-py2.py3-none-any.whl Collecting pyasn1-modules (from   service-identity==16.0.0)   Using cached   pyasn1_modules-0.0.8-py2.py3-none-any.whl Requirement already   satisfied: pyopenssl=0.12 in   /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python   (from service-identity==16.0.0) Collecting attrs (from   service-identity==16.0.0)   Using cached   attrs-16.3.0-py2.py3-none-any.whl Installing collected packages:   pyasn1, pyasn1-modules, attrs, service-identity Exception: Traceback   (most recent call last):   File   "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py",   line 215, in main       status = self.run(options, args)   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py",   line 342, in run       prefix=options.prefix_path,   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py",   line 784, in install       **kwargs   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py",   line 851, in install       self.move_wheel_files(self.source_dir, root=root, prefix=prefix)   File   "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py",   line 1064, in move_wheel_files       isolated=self.isolated,   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py",   line 345, in move_wheel_files       clobber(source, lib_dir, True)   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py",   line 316, in clobber       ensure_dir(destdir)   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/stronginit/strong.py",   line 83, in ensure_dir       os.makedirs(path)   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py",   line 157, in makedirs       mkdir(name, mode) OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pyasn1'   ol start="3" liHow do I fix this ERROR when I try to launch Deluge-Server?/li /ol 